### ISSUE TITLE
Admin culture picker

### ISSUE THREAD

**Issue by Skrypt** [sfmskywalker/Orchard#11]
The admin culture picker is not displaying anymore.

**Comment by agriffard** [comment]
This is because you don't have a zone in your Layout corresponding to Header : 
`@Display(Model.Header)`
and admin culture is injected there :
`_workContext.Layout.Header.Add(Shape.AdminCultureSelector(SupportedCultures: supportedCultures));`

There is no Footer zone either, in which we could put the OrchardVersion

**Comment by agriffard** [comment]
To have a dropdownlist with the culture, the AdminCultureSelector.cshtml view needs to be restored in TheAdmin theme.

**Comment by agriffard** [comment]
Or another way could be to make a picker rendered with flags of the corresponding countries.

**Comment by Skrypt** [comment]
I like having a list. It could be using a Bootstrap dropdown button and each culture could be a button item with an icon. We could switch the current culture flag on the button content.

![image](https://cloud.githubusercontent.com/assets/3228637/14474387/c4827d56-00ca-11e6-9c08-b48ea9540415.png)

Here is an example.

**Comment by agriffard** [comment]
Fixed in https://github.com/OrchardCMS/Orchard/commit/7c8ab76ec80d3a9e4252af688d07d8859215bbba

**Comment by agriffard** [comment]
Can be closed when you validate the display is correct.

**Comment by Skrypt** [comment]
after enabling the module and adding cultures I can see the culture picker.
Though I don't see any icons in the culture picker.

![image](https://cloud.githubusercontent.com/assets/3228637/16358717/d61159ee-3ae9-11e6-960b-d14f98faae5a.png)

**Comment by agriffard** [comment]
nano-content css fixed
