### ISSUE TITLE
Lists link in admin menu is #

### ISSUE THREAD

**Issue by agriffard** [sfmskywalker/Orchard#17]
The 'Lists' link doesn't redirect to admin/lists

**Comment by agriffard** [comment]
line 23 : 
`var firstLevelHref = "#";`
This would fix the problem :
`var firstLevelHref = firstLevelMenuItem.Href;`
but the 'new' menu link wouldn't be '#' anymore.

**Comment by Skrypt** [comment]
I think this one was fixed right ? @agriffard

**Comment by agriffard** [comment]
Yes but the fix implies that click on the New menu is as if you click on the first new sub menu.
