### ISSUE TITLE
Alias/IndexManaged : Last column is right aligned

### ISSUE THREAD

**Issue by agriffard** [sfmskywalker/Orchard#18]
In Admin/Alias/IndexManaged , the last column contains text and is aligned right because of the default css : 
` .table td:last-child { text-align: right; }`

**Comment by Skrypt** [comment]
I agree that we should'nt do that. It's a too large scope.

**Comment by Skrypt** [comment]
This one is fixed. We need to look if we need to apply text-right in some places now.

**Comment by agriffard** [comment]
Confirm it is fixed.
