### ISSUE TITLE
am-checkbox inline, inline is a colorbox function

### ISSUE THREAD

**Issue by donaldboulton** [sfmskywalker/Orchard#23]
am-checkbox inline
Should be
`am-checkbox display-inline`
Class Inline is a Colorbox function and when checked it brings up a Colorbox window.
suggest display-inline = that what its doing.
Works like this
`.am-checkbox.display-inline,
.am-radio.display-inline {
  display: inline-block;
}
.am-checkbox.display-inline + .am-checkbox.display-inline,
.am-checkbox.display-inline + .am-radio.display-inline,
.am-radio.display-inline + .am-checkbox.display-inline,
.am-radio.display-inline + .am-radio.display-inline {
  margin-left: 18px;
}`
please replace all occurrences of online.gif and offline.gif, they are just ugly, with s7 something.

Might add zones of a way to edit areas like in the sidebar with content items or mini-widgets.
Or like the new editable dashboard, would be way cool.
Super Nice Work Thanks!

**Comment by Skrypt** [comment]
Yes ! We need to clean up the HTML and use a better semantic. I think this is part of improving consistency in all views. We actually did the global work but we need to push another sprint on every modules/views to make it cleaner.
