### ISSUE TITLE
Admin Menu Settings dropdown too long

### ISSUE THREAD

**Issue by donaldboulton** [sfmskywalker/Orchard#24]
If you add modules that have settings then the list for the settings dropdown under
`<ul class="nav navbar-nav am-nav-right">`
Is to long, drops below the view port.
Maybe something like `<div class="am-scroller nano has-scrollbar">` could fix it
Urls in Orchard admin that are not under /Admin/ do not get shown as they are not a admin link.
As `/Orchard.OutputCache/Statistics` and a few others I do not recall which ones, "will check".

Created a issue in OrchardCMS [#6787](https://github.com/OrchardCMS/Orchard/issues/6787)

**Comment by Skrypt** [comment]
I suggest that we use the module feature panel boxes and add an icon to set up configurations per feature instead of adding menu items to that menu. We could keep it for general settings.
