### ISSUE TITLE
Stability and Publish errors because of [assembly: AssemblyVersion("1.0.0.0")]

### ISSUE THREAD

**Issue by donaldboulton** [sfmskywalker/Orchard#25]
Could not publish as Orchard.Dashboards could not find Orchard.Layouts because of `[assembly: AssemblyVersion("1.0.0.0")]` where Module.txt said 1.10.
 Fixed in [#6762](https://github.com/OrchardCMS/Orchard/issues/6762)
to correct version `[assembly: AssemblyVersion("1.10")]` and `[assembly: AssemblyFileVersion("1.10")]`
Changed all in this repository src; now it will publish.
Way Cool Admin Theme
Much faster than stock. Now no timeouts like I used to get; mostly because of the amount of files it took to make the old Admin Theme work.

**Comment by Skrypt** [comment]
I'm going to try and merge dev branch ; if those changes have been applied yet.

**Comment by Skrypt** [comment]
Merged now. You can pull latest changes that should fix this problem.

**Comment by donaldboulton** [comment]
Its 1.10 not dev with the updated AssemblyVersion

**Comment by Skrypt** [comment]
1.10 gets merged in dev from time to time.

**Comment by donaldboulton** [comment]
Nice now it publishes fine, can not find any issues. Time to merge it with 1.10.1. Even if the Steering Committee decides Amaretti could have a copyright issue; paneling the old Admin theme or Bootstrap Admin to work with the changes on the Core and Modules, would not be to hard.
I will pay the $18.00 for the Amaretti theme as Admin and a Front end theme. While you did the Admin I did it in a front end theme, I have added 23 Zones to cover All areas in the Amaretti Theme so Orchard.Layouts or widgets can be used:
Zones:Header, Messages, Featured, LocalNavigation, BeforeMain, Content, AfterContent, AsideSecond, AfterMain, FooterQuadFirst, FooterQuadSecond, FooterQuadThird, FooterQuadFourth, Footer, TopMessages, TopNotifications, TopConnections, SideBarTabOne, SideBarTabTwo, SidebarTabThree, SideBarTabFour, PopupHidden, RegistrationHidden
Using Amaretti classes for the zones. Smoking cool on Mobile.
Will have it to view in production tomorrow.

**Comment by Skrypt** [comment]
Be aware though that this is still a work in progress. There are things that still needs to be adjusted in this admin theme. I would say that this is risky to use it in production right now. Though this is your call :)

**Comment by donaldboulton** [comment]
Just for fun, using a unused old domain name. For Orchard users, "EVERYONE", test site.

**Comment by donaldboulton** [comment]
Try fixed left side menu, [Fixed left sidebar](http://themeslivepreview.com/amaretti/layouts-fixed-sidebar.php)
`<html lang="en">`
  `<body>`
   ` <div class="am-wrapper am-fixed-sidebar">`
I did, didn't like it to scroll with the page so its better for me and maybe for @sebastienros

**Comment by Skrypt** [comment]
I asked @sfmskywalker about this once and he said that we could add it as a setting to the theme. I will add a Trello task for this while you remember me this.
