### ISSUE TITLE
Responsive Tables, table-responsive

### ISSUE THREAD

**Issue by donaldboulton** [sfmskywalker/Orchard#28]
To be responsive and to view correctly.
`<div class="table-responsive">`
   `<table class="items table">`
       `....................`
    `</table>`
`</div>`
In `/Orchard.OutputCache/Statistics`
`/Warmup`
and some others
P.S.
Created a test site with this fork from 5 days ago = not latest;
With a front end and Admin Amaretti theme having 20 Zones to cover all Amaretti areas.
Will create a repository for my front end DB.Amaretti theme soon
Fixed the Sidebar Nav and added Aside Right which scroll independent of the page content, it has x-pjax push state, static and gzip dynamic compression and the proper headers not," Vary* " for x- pjax and gzip.
At publiuslogic.com
Role Author login is
User Name admin
Email admin@publiuslogic.com
Password adminuser

**Comment by Skrypt** [comment]
This is fixed, there is no more remaining tables without a div container that makes it overflow.
