### ISSUE TITLE
Edit Links need a class

### ISSUE THREAD

**Issue by donaldboulton** [sfmskywalker/Orchard#29]
`<span` class="btn btn-primary">`
        `href="/Admin/Blogs/12/Edit?class=remove&amp;returnUrl=%2FAdmin%2FNavigation` `Edit`
`</span>`
The link is the same color as the button, thus showing no text, as in the above Edit link.

**Comment by Skrypt** [comment]
I've not found anything like this in the views. I searched for <span class="btn btn-primary"> maybe that's a modification you made in the blog module for yourself. Else get me a screenshot and a way to see this.

**Comment by donaldboulton** [comment]
The latest download's are correct. Sorry must have been older files.
