### ISSUE TITLE
[new-admin-theme] Can't set field properties in new admin theme

### ISSUE THREAD

**Issue by Skrypt** [sfmskywalker/Orchard#3]
Can't set field properties in new admin theme.
Someone removed the field.cshtml editortemplate inclusion in the fields.cshtml editortemplate.
It is important to keep those editor templates.

**Comment by agriffard** [comment]
And field.cshtml also. It seems someone wanted to replace the expando by an accordion.

**Comment by agriffard** [comment]
Fixed in https://github.com/sfmskywalker/Orchard/commit/c06f83453a21ea37eb52198727ba30981d9e8296
