### ISSUE TITLE
Working on old version of Amaretti

### ISSUE THREAD

**Issue by donaldboulton** [sfmskywalker/Orchard#31]
Got the new version from yesterdays amaretti-v-1.1.5 release. If needed how to I send it to you? I am not putting it on GitHub, "for now", violation of purchase agreement.

**Comment by Skrypt** [comment]
Does it have noticeable improvements ? Yeah, don't put it on Github "bad idea". I will get it don't worry :smile:

**Comment by Skrypt** [comment]
We will get a special version of Amaretti from it's creator. Closing this issue for now since @sfmskywalker has pushed the latest version in the repo.

**Comment by sfmskywalker** [comment]
Which reminds me, there's even a "Orchard 1.6.1" version available. Should be easy to update to.
