### ISSUE TITLE
Content admin page : Filters and actions on different lines

### ISSUE THREAD

**Issue by agriffard** [sfmskywalker/Orchard#32]
In /Admin/Contents/List, the filters should be displayed on only on line when space is available (desktop and tablet screens).
Hence, the bulk actions and create buttons should be on another line below.

**Comment by Skrypt** [comment]
Yes it's not finished yet.

**Comment by Skrypt** [comment]
I must add that this is a bug because right now the filters are not binding to any controller actions. That's what's missing on this feature.

**Comment by agriffard** [comment]
Done but filters need to be fixed. They don't do anything.
