### ISSUE TITLE
Checkboxes are not displayed if there is an hidden input before the label

### ISSUE THREAD

**Issue by agriffard** [sfmskywalker/Orchard#37]
Checkboxes are not displayed if there is an hidden input before the label.

Ex : Try to create a blog and see 'Render a comments rss feed'

**Comment by agriffard** [comment]
It seems to happen with many checkboxes.
I don't understand why the @Html.Checkbox automatically adds an hidden input.
Is it the common behavior?

**Comment by Skrypt** [comment]
Yes

**Comment by Skrypt** [comment]
I think we can actually see this bug into the user edit view.

**Comment by agriffard** [comment]
All the Hml.EditorFor on a boolean are not displayed. I guess this is because of a script in the amarettir them that hides them but I can't find it. This is also because there is an hidden field after the input type="checkbox"

**Comment by agriffard** [comment]
Remove to specific css class in Assets/Less/Bootstrap/forms.less:
`input[type="checkbox"] + label, input[type="radio"] + `
Because the hidden input is between the checkbox and the label.
But I haven't really managed to relaunch the gulp task, so I updated TheAdmin.css for the moment.
Please test.

**Comment by agriffard** [comment]
I fixed the css correctly : adding ' + hidden ' between the checkbox and the label in the less file.

**Comment by agriffard** [comment]
'select all' checkboxes need to be fixed.

**Comment by agriffard** [comment]
Should be fixed now.

**Comment by agriffard** [comment]
radio button and boolean field display have to be fixed.

**Comment by agriffard** [comment]
Checkbox, Radio, boolean and enumeration field fixed.
