### ISSUE TITLE
Check No-content panels  

### ISSUE THREAD

**Issue by agriffard** [sfmskywalker/Orchard#38]
Check the "no-content" panels that @Skrypt and I added.

**Comment by agriffard** [comment]
and ensure they are all localizable, using a format string for example.

**Comment by Skrypt** [comment]
I'm not totally 100% sure they are all done. Some may be positioned wrong. They need to be outside of the content panel most of the time with some exceptions.

**Comment by Skrypt** [comment]
see https://github.com/OrchardCMS/Orchard/issues/7016
