### ISSUE TITLE
Content Type editing / Placement view

### ISSUE THREAD

**Issue by Skrypt** [sfmskywalker/Orchard#39]
That view needs to be worked. Right now the display is wrong. We would need to use Bootstrap panels that we could drag and drop.

**Comment by agriffard** [comment]
http://localhost:30321/OrchardLocal/Admin/ContentTypes/EditPlacement/BlogPost is not well displayed. 
h3 conflicts

**Comment by agriffard** [comment]
Should be good now.

**Comment by Skrypt** [comment]
I confirm
