### ISSUE TITLE
Users : sort icons not visible

### ISSUE THREAD

**Issue by agriffard** [sfmskywalker/Orchard#43]
http://localhost:30321/OrchardLocal/Admin/Users : 
On chrome, sort icons in the table head columns are not well displayed.

**Comment by agriffard** [comment]
same in http://localhost:30321/OrchardLocal/Admin/ContentTypes

**Comment by Skrypt** [comment]
I think we need to remove that functionnality. It's buggy. I tried fixing it but it make the design to break. I suggest we find a better js plugin to do that.

**Comment by agriffard** [comment]
I agree
