### ISSUE TITLE
Sub menu on touch screen

### ISSUE THREAD

**Issue by agriffard** [sfmskywalker/Orchard#6]
If the theme can be used with a touch screen (ex : on a phone), how can you display a sub menu that appears on mouse hover ?

**Comment by Skrypt** [comment]
Good catch Antoine. Can you help me fixing that one ? :)

**Comment by agriffard** [comment]
The issue appears because of the combined use of hover menus with parent links.
The impact is that when you are on a touch screen, you don't have a cursor and if you touch the link, it redirects the page.

If you want to keep the hover behavior, you have to provide a fallback for touch screens.
Here is a interesting approach :
http://osvaldas.info/drop-down-navigation-responsive-and-touch-friendly

When you touch the parent, the sub menu is shown because the touch event is handled and you can double touch the parent if you want to navigate to it.

This way, the menu would work on tablets (same display than desktop but sub menus would appear on touch) and on phones (with the off-canvas menu but you could tap on the parent links)

**Comment by agriffard** [comment]
I have tried to use this js trick but it is not really working.

In fact, I think it would be easier and usable to have the menu always displayed as the 'phone' media queries do and with the burger menu button visible to show/hide it.

I don't like the big menu icons, because I could see almost all the menu links without scrolling vertically as in the current (old) admin.

**Comment by miguelmich** [comment]
Hello guys,

I'm Miguel, the author of the admin template, I just wanted to let you know that I already have this issue on my list, and I think it's going to be fixed on the next release, I still need to do some tests in several tablets & touch devices.

Thanks :)

**Comment by agriffard** [comment]
I changed the left menu to not display large icons, but a menu with icon and label.
The sub menus are now displayed onclick, not onhover.

**Comment by Skrypt** [comment]
I think we can now close this one too. It fixes that problem.
